### ISSUE TITLE
How would you go about removing a worldborder?

### ISSUE THREAD

**Issue by TheSpeedCoder** [yannicklamprecht/WorldBorderAPI1.8-#9]
So far all the internet has to offer is set the worldborder to around 3000000 blocks but I think that's mad.
I'm using your API but there is no method to remove a border I'f you could point me in the right direction I would appreciate it.

**Comment by ysl3000** [comment]
Set the worldborder to around 3000000 blocks.

You can do it this way. Another approach will be a reset using the global world border.

**Comment by yannicklamprecht** [comment]
No response
